<div class='row'>
	<div class='col-md-3'></div>
		<div id='mitablero' class='col-md-3 tableros'>
			<h3>Piso 1</h3>
			<table class='table-bordered bg-info' id='tbluser'>
				<?php
				$data=$this->bnmodel->cargar1();
				if (isset($_POST['estado_aulas'])){
					$lahora=$_POST['estado_aulas'];
					echo "Datos para la hora: ";
					echo $lahora;
				}
				 ?>
			<?php for($i=1;$i<=5;$i++):?>
				<tr>
				<?php for($j=1;$j<=4;$j++):?>

					<td><button class='btn-info center-block btnuser' title="<?php
					if(4*($i-1)+$j-1<18){
						if (isset($_POST['estado_aulas'])){
							$lahora=$_POST['estado_aulas'];
							$data1=$this->bnmodel->cargardetalle($lahora);
							$data2=$this->bnmodel->cargarencargado($lahora);
							$this->session->data11=$data1;
							$this->session->data22=$data2;
						}
						$data1=$this->session->data11;
						$data2=$this->session->data22;
						if ($data[4*($i-1)+$j-1]==1){
							echo "Estado: Reservada";

						} else if ($data[4*($i-1)+$j-1]==2){
							echo "Estado: Ocupada";
						}
					     else if ($data[4*($i-1)+$j-1]==3){
							 echo "Estado: Libre";
					}
					  else if ($data[4*($i-1)+$j-1]==4){
						  echo "Estado: No Disponible";
						}
					   else if ($data[4*($i-1)+$j-1]==5){
						   echo "Estado: Alerta!!";
						}
				    echo "\r\n";echo " Detalle: ";
					echo $data1[4*($i-1)+$j];
					echo "\r\n";echo " Encargado: ";
					echo $data2[4*($i-1)+$j];
					}
					?>" type='button' id='pos-<?=(4*($i-1)+$j)?>' disabled="disabled" ><?=(4*($i-1)+$j)?></button></td>
				<?php endfor;?>
				</tr>
			<?php endfor;?>

			</table>
		</div>
		<div id='sutablero' class='col-md-3 tableros'>
			<h3>Piso 2</h3>
			<table class='table-bordered bg-warning' id='tblmachine'>
				<?php for($i=1;$i<=5;$i++):?>
				<tr>
				<?php for($j=1;$j<=4;$j++):?>

					<td><button class='btn-warning center-block btnmachine' type='button' id='supos-<?=(4*($i-1)+$j)?>' disabled="disabled"><?=(4*($i-1)+$j)?></button></td>
				<?php endfor;?>
				</tr>
			<?php endfor;?>

			</table>
		</div>
	<div class='col-md-3'></div>
</div>
<br><br><br><br>
<form method="post" action="">
<label >Hora</label>
<select name="estado_aulas">
<option>---Seleccione una Hora--</option>
<option value="h6_8">6-8</option>
<option value="h8_10">8-10</option>
<option value="h10_12">10-12</option>
<option value="h12_14">12-14</option>
<option value="h14_16">14-16</option>
<option value="h16_18">16-18</option>
</select>
</div>
<button type="submit" class="btn btn-info" name="consulta" >Submit</button>

</form>

<?php echo "<br>";  ?>
<?php echo "<br>";  ?>
<?php echo "<br>";  ?>
<div style="text-align:center">
	<form action="http://localhost:100/prafinal/index.php/auth/logout" method="post">
		<input class type='submit' name='submit' value='Salir'>
	</form>
</div>
