<!doctype html>
<html lang='es'>
	<head>
		<title>Practica Final</title>
		<meta charset='utf-8'>
		<link rel='stylesheet' href='<?php echo base_url()?>css/bootstrap.min.css'>
		<link rel='stylesheet' href='<?php echo base_url()?>css/bn.css'>
		<script src='<?php echo base_url()?>/js/jquery.min.js'></script>
		<script src='<?php echo base_url()?>/js/bootstrap.min.js'></script>
		<script src='<?php echo base_url()?>/js/bn.js'></script>
	</head>
	<body>
		<?=$content?>
	</body>
</html>
