<!doctype html>
<html>
	<head>
		<title>RT CHANNEL 1 - Ejemplo -</title>
		<meta charset="UTF-8">

				<script src="js/jquery.min.js"></script>
				<script src="js/pusher.min.js"></script>
				<script src='js/highcharts.js'></script>


				<link rel='stylesheet' href='<?php echo base_url()?>/css/bootstrap.min.css'>
				<link rel='stylesheet' href='<?php echo base_url()?>/css/bn.css'>
				<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">

				<script src='<?php echo base_url()?>/js/jquery.min.js'></script>
				<script src='<?php echo base_url()?>/js/bootstrap.min.js'></script>
				<script src='<?php echo base_url()?>/js/bn.js'></script>

				<script src="//code.jquery.com/jquery-1.10.2.js"></script>
				<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
			</head>
			<body>
				<div id="dialog" class="hide" title="Alert">
					<p> El Juego Va a Iniciar</p>
				</div

				<div id="dialog1" class="hide" title="Alert">
					<p> El JUgador 2 No ha puesto todos los barcos</p>
				</div

				<div id="dialog2" class="hide" title="Alert">
					<p> El JUgador 1 No ha puesto todos los barcos</p>
				</div

				test
				<?=$content?>
				<!-- <div class='bg-danger'>Consulta:&nbsp;<?=$pruebasbd?></div> -->
			</body>
		</html>
